# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "akanto/centos-7"

  if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end

  config.vm.define "controller-vagrant" do |controller|
    controller.vm.hostname = "controller-vagrant"
    controller.vm.network "private_network", ip: "10.0.0.11"
    controller.vm.provider :virtualbox do |vbcontroller|
        vbcontroller.customize ["modifyvm", :id, "--memory", "4096"]
        vbcontroller.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

 # config.vm.define "network1-vagrant" do |network1|
 #  network1.vm.hostname = "network1-vagrant"
 #   network1.vm.network "private_network", ip: "10.0.0.21"
 #   network1.vm.network "private_network", ip: "10.0.1.21"
 #   network1.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
 #    network1.vm.provision "shell", inline: "route del default && route add default gw 192.168.1.1 eth3"
 # end

  (1..2).each do |i|
    config.vm.define "compute#{i}-vagrant" do |node|
      node.vm.hostname = "compute#{i}-vagrant"
      node.vm.network "private_network", ip: "10.0.0.3#{i}"
      node.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
          disk = ".vagrant/cinder-disk-#{i}.vdi"
          unless File.exist?(disk)
            vb.customize ['createhd', '--filename', disk, '--size', 30 * 1024]
          end
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
      end
    end
  end

  config.vm.provision :ansible do |ansible|
        ansible.groups = {
           "vagrant-openstack" => ["controller-vagrant", "compute1-vagrant", "compute2-vagrant"]
        }
        #ansible.playbook = "../../ansible/os-controller.yml"
        #ansible.playbook = "../../ansible/os-compute.yml"
        ansible.playbook = "../../ansible/openstack-multi.yml"
        ansible.raw_arguments = "--diff"
        #ansible.verbose = "vvv"
        #ansible.tags = ["restart-components"]
        ansible.skip_tags = ["restart-components"]
  end

end
