---
- name: install mariadb
  yum: name={{ item }} state=latest
  become: true
  register: mariadb_updated
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: write the mariadb config file
  template: src=mariadb_openstack.cnf.j2 dest=/etc/my.cnf.d/mariadb_openstack.cnf backup=yes
  become: true
  notify:
    - restart mariadb

- name: Trigger handlers
  meta: flush_handlers

- name: ensure mariadb is running
  become: true
  service: name=mariadb state=started enabled=yes


#  This can be executed non ineractively only in version 5.7.x
#- name: secure installation
#  become: true
#  command: mysql_secure_installation && touch /etc/mysql/mysql_secure_installation
#  args:
#    creates: /etc/mysql/mysql_secure_installation


# mysql_secure_installation

- name: delete anonymous MariaDB server user for {{ ansible_hostname }}
  mysql_user:
    login_user: root
    login_password: ""
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ inventory_hostname }}"
    - localhost
    - 127.0.0.1
    - ::1
    - "%"
  when: mariadb_updated.changed

- name: remove the MariaDB test database
  mysql_db:
    login_user: root
    login_password: ""
    db: test
    state: absent
  when: mariadb_updated.changed

- name: DB setup
  include: db.yml

- name: restart openstack-db by handlers
  shell: echo 'Restarting openstack-db(mariadb)....'
  tags:
    - restart-components
  notify:
    - restart mariadb
