---
- name: create glance_root
  file: path={{ glance_root }}/var/{{ item }} state=directory mode=0755
  become: true
  with_items:
    - lib

- name: install glance
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - openstack-glance
    - python-glance
    - python-glanceclient

- name: write glance-api.conf file
  template: src=glance-api.conf.j2 dest=/etc/glance/glance-api.conf backup=yes
  become: true
  register: write_glance_api_conf
  notify:
    - populate glancedb
    - restart glance-api

- name: write glance-registry.conf file
  template: src=glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf backup=yes
  become: true
  notify:
    - populate glancedb
    - restart glance-registry

- name: copy glance files to another location
  shell: cp -r /var/lib/glance {{ glance_root }}/var/lib/glance && chown -R glance:glance {{ glance_root }}/var/lib/glance creates={{ glance_root }}/var/lib/glance
  become: true
  when: write_glance_api_conf.changed

- name: Trigger handlers
  meta: flush_handlers

- name: ensure glance services are running
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - openstack-glance-api
    - openstack-glance-registry

- name: Setup Glance entities
  include: glance-init.yml

- name: restart glance components by handlers
  shell: echo 'Restarting glance components....'
  tags:
    - restart-components
  notify:
    - restart glance-api
    - restart glance-registry
