---
- name: install neutron
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - openstack-neutron-openvswitch
    - ebtables

- name: write neutron config files
  template: src=neutron/{{ item }}.j2 dest=/etc/neutron/{{ item }}
  become: true
  with_items:
    - l3_agent.ini
    - dhcp_agent.ini
    - metadata_agent.ini
    - dnsmasq-neutron.conf
  notify:
    - restart neutron server

- name: write plugin config files
  template: src=neutron/plugins/ml2/{{ item }}.j2 dest=/etc/neutron/plugins/ml2/{{ item }}
  become: true
  with_items:
    - linuxbridge_agent.ini
  notify:
    - restart neutron server


#- name: create ovs-init
#  become: true
#  template: src=scripts/ovs-init.sh.j2 dest=/opt/scripts/ovs-init.sh mode="a+x"
#  register: ovs_init
#
#- name: execute ovs-init
#  become: true
#  shell: /opt/scripts/ovs-init.sh
#  when: ovs_init.changed

