---
- name: populate novadb
  become: true
  shell: /bin/sh -c "nova-manage db sync" nova

- name: populate novaapi_db
  become: true
  shell: /bin/sh -c "nova-manage api_db sync" nova

- name: restart nova controller
  become: true
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-consoleauth
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy