---
- name: install qemu
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - qemu

- name: install nova components
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - openstack-nova-compute
    - sysfsutils

- name: create nova_root
  file: path={{ nova_root }}/var/{{ item }} state=directory mode=0755 owner=nova group=nova
  become: true
  with_items:
    - lib

- name: copy nova files to another location
  command: creates="{{ nova_root }}/var/lib/nova" mv /var/lib/nova {{ nova_root }}/var/lib/nova
  become: true

- name: write the nova config file
  template: src={{ item }}.j2 dest=/etc/nova/{{ item }} backup=yes
  become: true
  register: write_nova_conf
  notify:
    - restart nova compute
  with_items:
    - nova.conf

- name: Trigger handlers
  meta: flush_handlers

- name: ensure nova services are running
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - libvirtd
    - openstack-nova-compute

- name: restart nova components by handlers
  shell: echo 'Restarting nova components....'
  tags:
    - restart-components
  notify:
    - restart nova compute
