---
- name: disable selinux
  become: true
  selinux: state=permissive policy=targeted

#- name: permissive firewalld
#  become: true
#  firewalld: source={{ firewalld_source }} zone=public permanent=true state=enabled

- name: ensure firewalld is not running
  become: true
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - firewalld

- name: install epel release repo
  yum: name=epel-release state=latest
  become: true

- name: install basic utilities
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - chrony
    - sysstat
    - tree
    - traceroute
    - iperf
    - net-tools
    - which

- name: ensure chronyd is running
  become: true
  service: name=chronyd state=started enabled=yes

- name: install openstack newton repo
  become: true
  yum: name=centos-release-openstack-newton state=present

- name: install openstack-selinux
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - openstack-selinux

- name: creates installed directory to keep track what has already been installed
  file: path={{ installed_dir }} state=directory
  become: true
