---
- name: install raid utilities
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - lvm2

- name: ensure lvm2-lvmetad  is running running
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - lvm2-lvmetad

- name: Creates scripts
  become: true
  file: path=/opt/scripts state=directory mode="a+x"

- name: add raid script
  become: true
  template: src=scripts/diskcfg.sh.j2 dest=/opt/scripts/diskcfg.sh mode="a+x"
