---
- name: install cinder controller components
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - openstack-cinder
    - python-cinderclient
    - python-oslo-db

- name: Creates scripts
  become: true
  file: path=/opt/scripts state=directory mode="a+x"

- name: create cinder-entities
  become: true
  template: src=scripts/cinder-init.sh.j2 dest=/opt/scripts/cinder-init.sh mode="a+x"
  register: cinder_entities

- name: execute cinder-entities
  shell: /opt/scripts/cinder-init.sh
  when: cinder_entities.changed

- name: write the cinder config file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf backup=yes
  become: true
  notify:
    - populate cinderdb
    - restart cinder controller

- name: Trigger handlers
  meta: flush_handlers

- name: ensure cinder controller services are running
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - openstack-cinder-scheduler
    - openstack-cinder-api

- name: restart cinder components by handlers
  shell: echo 'Restarting cinder components....'
  tags:
    - restart-components
  notify:
    - restart cinder controller