# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["createhd",  "--filename", "raid_disk0", "--size", "2048"]
    vb.customize ["createhd",  "--filename", "raid_disk1", "--size", "2048"]
    vb.customize ["createhd",  "--filename", "raid_disk2", "--size", "2048"]
    vb.customize ["createhd",  "--filename", "raid_disk3", "--size", "2048"]
    vb.customize ["createhd",  "--filename", "raid_disk4", "--size", "2048"]
    vb.customize ["storageattach", :id, "--storagectl", "SATAController", "--port", "1", "--type", "hdd", "--medium", "raid_disk0.vdi"]
    vb.customize ["storageattach", :id, "--storagectl", "SATAController", "--port", "2", "--type", "hdd", "--medium", "raid_disk1.vdi"]
    vb.customize ["storageattach", :id, "--storagectl", "SATAController", "--port", "3", "--type", "hdd", "--medium", "raid_disk2.vdi"]
    vb.customize ["storageattach", :id, "--storagectl", "SATAController", "--port", "4", "--type", "hdd", "--medium", "raid_disk3.vdi"]
    vb.customize ["storageattach", :id, "--storagectl", "SATAController", "--port", "5", "--type", "hdd", "--medium", "raid_disk4.vdi"]

  end

  config.vm.define "raid" do |raid|
      raid.vm.hostname = "raid"
  end

end
