---
- name: install cinder storage node components
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - qemu
    - lvm2
    - openstack-cinder
    - targetcli
    - python-oslo-db
    - python-oslo-log
    - MySQL-python

- name: ensure lvm2-lvmetad  is running running
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - lvm2-lvmetad

- name: create volume group for cinder
  become: true
  lvg: vg=cinder-volumes pvs={{ cinder_volumes }}
  when: cinder_volumes | default("") != ""

- name: write the cinder config file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf backup=yes
  become: true
  notify:
    - restart cinder storage node services

- name: The /var/lock/cinder does not exsist, therefore the volumes are not deleted
  become: true
  file: path=/var/lock/cinder state=directory owner=cinder group=cinder

- name: Trigger handlers
  meta: flush_handlers

- name: ensure cinder storage services are running
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - openstack-cinder-volume
    - target

- name: restart cinder-storage components by handlers
  shell: echo 'Restarting cinder-storage components....'
  tags:
    - restart-components
  notify:
    - restart cinder storage node services
