---
- name: upgrade all packages
  sudo: true
  yum: name=* state=latest

- name: register running kernel version
  command: uname -r
  changed_when: false
  register: running_kernel

- name: register installed kernel version
  sudo: true
  shell: yum list kernel | grep kernel.x86_64 | tail -1 | awk '{print $2}'
  register: installed_kernel
  changed_when: installed_kernel.stdout != running_kernel.stdout

#- name: reboot if kernel version has changed
#  include: reboot.yml
#  when: installed_kernel.stdout != running_kernel.stdout
