# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provision "shell", inline: "route del default && route add default gw 192.168.1.1 eth1"
  #config.vm.provision "shell", inline: "route add -net 216.0.0.0 netmask 255.0.0.0  dev eth1"

  config.vm.define "ovsvm" do |ovsvm|
    ovsvm.vm.hostname = "ovsvm"
  end

  config.vm.provision :ansible do |ansible|
        ansible.playbook = "../../ansible/local-vagrant.yml"
        # ansible.verbose = "v"
  end



end
